### ISSUE TITLE
Como Criar um Ambiente de Desenvolvimento com Docker

### ISSUE THREAD

**Issue by esron** [Sysvale/community-program#2]
Uma palestra de no máximo 30 minutos explicando conceitos básicos de Docker para ambiente de desenvolvimento.

Já foi aceita no DevSertão.

Vai ao ar no dia 15/05, no [canal do DevSertão](https://www.youtube.com/channel/UCmTj8p91sON9wCu7mkMpLVg)

**Comment by geidsonc** [comment]
O docker é uma das principais ferramentas do nosso dia a dia de desenvolvimento. Sua palestra tirou várias dúvidas para quem está começando. Valeu

**Comment by gab0gomes** [comment]
Pontos creditados!
