### ISSUE TITLE
PHP através do Framework Laravel.

### ISSUE THREAD

**Issue by gilmaracastro** [Sysvale/community-program#5]
### Descrição

- Oficina a ser apresentado no evento de [`Programação para jovens desenvolvedores`](https://www.sympla.com.br/programacao-para-jovens-desenvolvedores---oficina-2__1304492)

### Dia 
- 23 e 24/08/2021

### Horário 
- 8h às 12hrs

**Comment by geidsonc** [comment]
Aceita
