### ISSUE TITLE
Minha história com a tecnologia

### ISSUE THREAD

**Issue by gilmaracastro** [Sysvale/community-program#7]
### Descrição

Desde o primeiro algoritmo escrito por Ada Lovelace até os dias de hoje, nós mulheres buscamos meios de nos destacar na construção de nossas carreiras, principalmente dentro do segmento tecnológico que é um lugar majoritariamente masculino. Os desafios de trabalhar com tecnologia são intensos e diários. Nesta palestra, você irá conhecer um pouco dos meus desafios e conquistas. Espero inspirar outras mulheres nessa carreira.

### Dia
- `28/09/2021`
 
Mais informações em: https://www.sympla.com.br/meetup-reprograma-58__1357488

**Comment by geidsonc** [comment]
Aceito
